import { Image } from "expo-image";
import { useRouter } from "expo-router";
import { FileText, Search, TrendingUp, Video, X } from "lucide-react-native";
import { useState } from "react";
import { ActivityIndicator, FlatList, ScrollView, TextInput, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Glass } from "@/components/layout/Glass";
import { XapXapHeader } from "@/components/layout/XapXapHeader";
import { Avatar } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Icon } from "@/components/ui/icon";
import { Text } from "@/components/ui/text";
import { useAuth } from "@/contexts/auth-context";
import { usePopularTags, useTrendingWaves } from "@/features/search/services/queries";
import { useColors } from "@/hooks/use-colors";

export function SearchScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  const router = useRouter();
  const { session, showAuthModal } = useAuth();
  const [query, setQuery] = useState("");

  const { data: trendingWaves = [], isLoading: isLoadingWaves } = useTrendingWaves();
  const { data: popularTags = [], isLoading: isLoadingTags } = usePopularTags();

  const trimmedQuery = query.trim().toLowerCase();
  const filteredWaves = trimmedQuery
    ? trendingWaves.filter(
        (wave) =>
          wave.content?.toLowerCase().includes(trimmedQuery) ||
          wave.author.toLowerCase().includes(trimmedQuery)
      )
    : trendingWaves;

  const handlePressWave = (id: string) => {
    if (!session) return showAuthModal();
    // biome-ignore lint/suspicious/noExplicitAny: Route type not yet generated by expo-router
    router.push({ pathname: "/post/[id]", params: { id } } as any);
  };

  const renderMediaThumbnail = (mediaUrl: string | null, mediaType: string | null) => {
    if (!mediaUrl) return null;

    if (mediaType?.startsWith("video/")) {
      return (
        <View className="w-full h-24 rounded-xl overflow-hidden mb-3 bg-zinc-900">
          <Image
            source={{ uri: mediaUrl }}
            style={{ width: "100%", height: "100%" }}
            contentFit="cover"
          />
          <View className="absolute inset-0 items-center justify-center">
            <View className="w-10 h-10 rounded-full bg-black/50 items-center justify-center">
              <Icon as={Video} size={18} className="text-white" />
            </View>
          </View>
        </View>
      );
    }

    if (
      mediaType === "application/pdf" ||
      mediaType === "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    ) {
      return (
        <View className="w-full h-16 rounded-xl mb-3 bg-zinc-900 flex-row items-center px-4 gap-3">
          <Icon as={FileText} size={24} className="text-primary" />
          <Text className="text-foreground/80 text-xs font-medium" numberOfLines={1}>
            Document
          </Text>
        </View>
      );
    }

    return (
      <View className="w-full h-24 rounded-xl overflow-hidden mb-3 bg-zinc-900">
        <Image
          source={{ uri: mediaUrl }}
          style={{ width: "100%", height: "100%" }}
          contentFit="cover"
        />
      </View>
    );
  };

  return (
    <View className="flex-1 bg-background" style={{ paddingTop: insets.top }}>
      <XapXapHeader />

      <View className="px-6 py-2">
        <View className="bg-muted rounded-full flex-row items-center px-5 h-14 border border-border">
          <Icon as={Search} size={20} className="text-muted-foreground mr-3" />
          <TextInput
            value={query}
            onChangeText={setQuery}
            placeholder="Search waves, people, #tags..."
            placeholderTextColor={colors.mutedForeground}
            className="flex-1 h-full text-foreground font-medium text-base"
            autoCapitalize="none"
          />
          {query.length > 0 && (
            <Button
              variant="ghost"
              onPress={() => setQuery("")}
              className="p-0 min-w-0 min-h-0 h-auto w-auto bg-transparent active:bg-transparent">
              <Icon as={X} size={20} className="text-muted-foreground" />
            </Button>
          )}
        </View>
      </View>

      <ScrollView
        className="flex-1"
        contentContainerStyle={{ paddingBottom: insets.bottom + 120 }}
        showsVerticalScrollIndicator={false}>
        {/* Popular Tags Section */}
        <View className="mt-6">
          <View className="px-6 mb-6">
            <Text className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground mb-4">
              Popular Tags
            </Text>
            {isLoadingTags ? (
              <ActivityIndicator color={colors.primary} />
            ) : (
              <View className="flex-row flex-wrap gap-2.5">
                {popularTags.map((tag) => (
                  <Button
                    key={tag.id}
                    variant="ghost"
                    onPress={() => setQuery(tag.tag)}
                    className="bg-muted border border-border rounded-full active:bg-secondary p-0 min-w-0 min-h-0 h-auto w-auto">
                    <View className="flex-row items-center gap-1.5 px-4 py-2.5">
                      <Text className="text-foreground text-sm font-semibold">{tag.tag}</Text>
                      <Text className="text-muted-foreground text-[10px] font-medium">
                        • {tag.count} drops
                      </Text>
                    </View>
                  </Button>
                ))}
              </View>
            )}
          </View>
        </View>

        {/* Trending Waves Section */}
        <View className="mt-4">
          <View className="px-6 mb-4">
            <Text className="text-[10px] font-bold uppercase tracking-widest text-muted-foreground">
              Trending Waves
            </Text>
          </View>

          {isLoadingWaves ? (
            <View className="h-40 items-center justify-center">
              <ActivityIndicator color={colors.primary} />
            </View>
          ) : filteredWaves.length === 0 ? (
            <View className="px-6 py-10 items-center">
              <Text className="text-muted-foreground">No waves found for "{query.trim()}".</Text>
            </View>
          ) : (
            <FlatList
              horizontal
              data={filteredWaves}
              keyExtractor={(item) => item.id}
              showsHorizontalScrollIndicator={false}
              contentContainerStyle={{ paddingHorizontal: 20 }}
              renderItem={({ item }) => (
                <Button
                  variant="ghost"
                  onPress={() => handlePressWave(item.id)}
                  className="p-0 min-w-0 min-h-0 h-auto w-auto bg-transparent active:bg-transparent">
                  <Glass radius={24} className="w-64 p-5 mr-4 border border-border bg-muted">
                    <Button
                      variant="ghost"
                      onPress={(e) => {
                        e.stopPropagation();
                        router.push({
                          pathname: "/profile/[id]",
                          params: { id: item.authorId, username: item.author },
                        });
                      }}
                      className="flex-row items-center mb-3 p-0 min-w-0 min-h-0 h-auto w-auto bg-transparent active:bg-transparent">
                      <Avatar username={item.author} size={32} />
                      <Text className="ml-3 font-bold text-foreground text-sm">@{item.author}</Text>
                    </Button>
                    {renderMediaThumbnail(item.mediaUrl, item.mediaType)}
                    <View className="flex-1">
                      <Text className="text-foreground/80 text-sm leading-5" numberOfLines={2}>
                        {item.content}
                      </Text>
                    </View>
                    <View className="flex-row items-center mt-3">
                      <Icon as={TrendingUp} size={14} className="text-primary mr-1.5" />
                      <Text className="text-primary font-bold text-xs">{item.buzz} buzz</Text>
                    </View>
                  </Glass>
                </Button>
              )}
            />
          )}
        </View>
      </ScrollView>
    </View>
  );
}
